# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

FROM python:3.7

WORKDIR /usr/src/flowapi
# Note: the flowkit_common/ folder must be copied manually into the flowapi/ folder
# so that docker can pick it up here. This is a temporary workaround until flowkit_common
# can be installed from PyPI.
COPY ./flowkit_common /usr/src/flowkit_common/
COPY Pipfile* /
RUN pip install pipenv && pipenv install --dev
COPY . /flowapi/
RUN pipenv install --skip-lock .
ENV QUART_ENV=development
CMD pipenv run hypercorn --debug --reload --bind 0.0.0.0:9090 "flowapi.main:create_app()"
